version: '3.8'

services:
  goodbaby:
    image: mei232/goodbaby:latest
    ports:
      - "8088:8088"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./config.json:/app/config.json:ro

networks:
  app-network:
    driver: bridge